In [1]:
import numpy as np
print("Вправа 1. Вводиться число n. Вивести масив разміра nхn, в якому по діагоналі йдуть числа від 1 до n, а інші числа рівні 0")
n = int(input("n: "))
diag = np.arange(1,n+1,1)
print(np.diag(diag))

Вправа 1. Вводиться число n. Вивести масив разміра nхn, в якому по діагоналі йдуть числа від 1 до n, а інші числа рівні 0
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
print("Вправа 3. Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в якому в кожному r -му рядку і в кожному c-му стовбчику стоять 0,а інші елементи дорівнюють 1.")
n = int(input())
m = int(input())
r = int(input())
c = int(input())
arr = np.ones((n, m))
arr[::r] = 0
arr[:, ::c] = 0
print(arr)

Вправа 3. Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в якому в кожному r -му рядку і в кожному c-му стовбчику стоять 0,а інші елементи дорівнюють 1.
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [6]:
print("Вправа 6. З клавіатури вводиться масив. Замінити всі ненульові елементи на -1.")
arr = np.array(input().split(), dtype =int)
arr[arr!=0]=-1
print(arr)

Вправа 6. З клавіатури вводиться масив. Замінити всі ненульові елементи на -1.
[-1 -1 -1  0 -1  0 -1  0]


In [9]:
print("Вправа 8. З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульвих елементів.")
n = [int(i) for i in input().split()]
x = np.array(n)
print('Нулів: ', len(x[x == 0]))
print('Не нулів: ', len(x[x != 0]))
   

Вправа 8. З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульвих елементів.
Нулів:  3
Не нулів:  4


In [10]:
print("Вправа 12. Створити масив одиниць розміром n х n та створити в ньому «рамку», сформовану з 0.")
n = int(input('Введите размерность матрицы '))
arr = np.ones((n, n), dtype=float)
arr[:1:] = 0
arr[-1:] = 0
arr[::1,0:1] = 0
arr[::1,-1::] = 0
print(arr)

Вправа 12. Створити масив одиниць розміром n х n та створити в ньому «рамку», сформовану з 0.
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
print("Визначити індекс 100 елемента в лінійному масиві, якщо його перетворять у матрицю розміром 4х5х6.")
arr = np.empty(120)
filler = np.arange(1,120,1)
index = np.arange(arr.size)
np.put(arr,index,filler)
newArr = np.reshape(arr, (4,5,6))
print(np.where(newArr == 100))

Визначити індекс 100 елемента в лінійному масиві, якщо його перетворять у матрицю розміром 4х5х6.
(array([3], dtype=int64), array([1], dtype=int64), array([3], dtype=int64))


In [18]:
print("Вправа 16. Заповнити парні стовбчики матриці розміром n х n одиницями, а непарні – нулями.")
n = int(input())
arr = np.empty((n, n), dtype=np.int8)
arr[:, ::2] = 0
arr[:, 1::2] = 1
print(arr)

Вправа 16. Заповнити парні стовбчики матриці розміром n х n одиницями, а непарні – нулями.
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [21]:
print("Вправа 18. Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значеннь, що менші за n/2 та більші за 3n/4 на протилежні")
n = int(input())
arr = np.arange(0,n+1)
arr[(arr < n/2) ^ (arr > 3*n/4)] *= -1
print(arr)

Вправа 18. Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значеннь, що менші за n/2 та більші за 3n/4 на протилежні
[ 0 -1 -2 -3  4  5 -6 -7]


In [25]:
print("Вправа 20. Згенерувати вектор із n елементів, що рівномірно розміщені на інтервалі (0,1) – тобто обидва кінці інтервалу не включені. Значення вивести до 3 знаків після коми.")
n = int(input())
arr = np.linspace(0,1,n)[1:-1]
print(arr)

Вправа 20. Згенерувати вектор із n елементів, що рівномірно розміщені на інтервалі (0,1) – тобто обидва кінці інтервалу не включені. Значення вивести до 3 знаків після коми.
[0.5]


In [27]:
print("Вправа 22. Ввести числа n і m. Згенерувати матрицю n на n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.")
n = int(input())
m = int(input())
matr = np.random.randint(0, m+1, (n, m))
print('Початковий вектор\n', matr)
matr[matr == np.max(matr)] *= -1
print('Змінений вектор\n', matr)

Вправа 22. Ввести числа n і m. Згенерувати матрицю n на n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.
Початковий вектор
 [[4 4 0 1 2]
 [2 5 4 4 3]
 [4 3 4 1 5]]
Змінений вектор
 [[ 4  4  0  1  2]
 [ 2 -5  4  4  3]
 [ 4  3  4  1 -5]]


In [29]:
print("2. Розв’язати систему за допомогою формул Крамера і виконати перевірку задопомогою: a) матричного множення; b) функції numpy.linalg.solv(.")
sl = np.array([[2, -6, 2, 2, 12], [1, 3, 5, 7, 12], [3, 5, 7, 1, 0], [5, 7, 1, 3, 4]])
det_0 = np.linalg.det(sl[:,:4])
det_1 = np.linalg.det(np.concatenate((sl[:,4:5], sl[:,1:4]), axis=1))
det_2 = np.linalg.det(np.concatenate((np.concatenate((sl[:, 0:1], sl[:,4:5]), axis=1), sl[:, 2:4]), axis=1))
det_3 = np.linalg.det(np.concatenate((np.concatenate((sl[:, 0:2], sl[:,4:5]), axis=1), sl[:, 3:4]), axis=1))
det_4 = np.linalg.det(np.concatenate((sl[:, :3], sl[:, 4:5]), axis=1))
x1 = det_1 / det_0
x2 = det_2 / det_0
x3 = det_3 / det_0
x4 = det_4 / det_0
x = np.array([x1, x2, x3, x4])
print('Рiшення системи:\nX =', x)
print('Перевiрка матричним множенням (A * X) = :\n', np.dot(sl[:, :4], x))
print('Перевiрка за допомогою функції linalg.solve():\n', np.linalg.solve(sl[:, :4], sl[:, 4:5]))

2. Розв’язати систему за допомогою формул Крамера і виконати перевірку задопомогою: a) матричного множення; b) функції numpy.linalg.solv(.
Рiшення системи:
X = [ 1.00000000e+00 -1.00000000e+00 -9.36750677e-17  2.00000000e+00]
Перевiрка матричним множенням (A * X) = :
 [1.20000000e+01 1.20000000e+01 1.77635684e-15 4.00000000e+00]
Перевiрка за допомогою функції linalg.solve():
 [[ 1.00000000e+00]
 [-1.00000000e+00]
 [-1.01770444e-16]
 [ 2.00000000e+00]]


In [7]:
print("3. Обчислити значення матричного виразу.")
a = np.array([[2,1,3], [1,-2,0], [4,-3,0]])
b = np.array([[22,-14,3], [6,-7,0], [11,3,15]])
print('A =', a, '\nB =', b)
print('3*(A + B)*(AB - 2A) =\n', 3*np.dot((a+b),(np.dot(a,b)) - np.dot(2,a)))

A = [[ 2  1  3]
 [ 1 -2  0]
 [ 4 -3  0]] 
B = [[ 22 -14   3]
 [  6  -7   0]
 [ 11   3  15]]
3*(A + B)*(AB - 2A) =
 [[ 6492 -2694  3339]
 [ 1443  -696   864]
 [ 6345 -2565  2565]]


In [30]:
print("4. Розв’язати рівняння за допомогою оберненої матриці і виконати перевірку за допомогою: a) матричного множення;b) функції numpy.linalg.solve().")
a = np.array([[2, 3, -1], [4,5,2], [-1,0,7]])
b = np.array([[-1,0,5], [2, 1, 3], [0,-2, 4]])
inv_a = np.linalg.inv(a)
x = np.dot(inv_a, b)
print('Рiшення рiвняння X =\n', x)
print('Перевiрка матричним множенням A * X =\n', np.dot(a, x))
print('Перевiрка за допомогою функції linalg.solve():\n', np.linalg.solve(a, b))

4. Розв’язати рівняння за допомогою оберненої матриці і виконати перевірку за допомогою: a) матричного множення;b) функції numpy.linalg.solve().
Рiшення рiвняння X =
 [[ 3.08  1.72 -6.24]
 [-2.24 -1.16  5.72]
 [ 0.44 -0.04 -0.32]]
Перевiрка матричним множенням A * X =
 [[-1.00000000e+00  4.44089210e-16  5.00000000e+00]
 [ 2.00000000e+00  1.00000000e+00  3.00000000e+00]
 [-5.55111512e-17 -2.00000000e+00  4.00000000e+00]]
Перевiрка за допомогою функції linalg.solve():
 [[ 3.08  1.72 -6.24]
 [-2.24 -1.16  5.72]
 [ 0.44 -0.04 -0.32]]
